"""initial tables create

Revision ID: 28b1bf26fa80
Revises: 
Create Date: 2022-07-30 01:52:05.488377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b1bf26fa80'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('hash', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('species', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('origin', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('episode', sa.String(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('created', sa.String(length=64), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('episodes', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('hash', 'id')
    )
    op.create_table('episodes',
    sa.Column('hash', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('air_date', sa.String(length=128), nullable=True),
    sa.Column('episode', sa.String(length=128), nullable=True),
    sa.Column('characters', sa.String(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('created', sa.String(length=128), nullable=True),
    sa.Column('link', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('hash', 'id')
    )
    op.create_table('locations',
    sa.Column('hash', sa.String(length=128), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('dimension', sa.String(length=64), nullable=True),
    sa.Column('residents', sa.String(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('created', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('hash', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations')
    op.drop_table('episodes')
    op.drop_table('characters')
    # ### end Alembic commands ###
