"""image for episode

Revision ID: 4f40754f69d7
Revises: 28b1bf26fa80
Create Date: 2022-07-31 23:50:56.538053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f40754f69d7'
down_revision = '28b1bf26fa80'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episodes', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('episodes', 'image')
    # ### end Alembic commands ###
